version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CMS
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  strapi:
    build:
      context: .
    volumes:
      - ./:/app
      - ./app/node_modules
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: CMS
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      APP_KEYS: your-app-key
      API_TOKEN_SALT: your-api-token-salt
      ADMIN_JWT_SECRET: your-admin-jwt-secret
      JWT_SECRET: your-jwt-secret
    depends_on:
      - postgres
    command: npm run develop

volumes:
  postgres_data:
